//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YT.Generate.Cuts.Application.VideoProcessing.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Prompts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Prompts() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YT.Generate.Cuts.Application.VideoProcessing.Resources.Prompts", typeof(Prompts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You are a technical video editing assistant focused on TikTok, Reels, and Shorts. Your only function is to extract exact timestamps from the provided subtitles.
        ///Video context: &apos;[VIDEO_TITLE]&apos;
        ///
        ///CRITICAL RULES:
        ///1. DO NOT invent times. Use ONLY the times (HH:mm:ss) that appear explicitly in the subtitle text.
        ///2. SHORT FORMAT: The cut MUST be between 15 and 60 seconds (only a few lines of subtitles).
        ///3. The generated text for &apos;reason&apos; and &apos;name&apos; MUST be in English and MUST reflect the actual subject discu [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string SystemCutPrompt {
            get {
                return ResourceManager.GetString("SystemCutPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [START OF SUBTITLES]
        ///[SUB_CHUNK]
        ///[END OF SUBTITLES]
        ///
        ///Based on the subtitles above, extract the viral cuts.
        ///
        ///EXPECTED FORMAT EXAMPLE:
        ///{{
        ///  &quot;&quot;cuts&quot;&quot;: [
        ///    {{
        ///      &quot;&quot;init&quot;&quot;: &quot;&quot;00:01:10&quot;&quot;,
        ///      &quot;&quot;end&quot;&quot;: &quot;&quot;00:01:45&quot;&quot;,
        ///      &quot;&quot;reason&quot;&quot;: &quot;&quot;The speaker makes a shocking revelation about how the economy affects small businesses.&quot;&quot;,
        ///      &quot;&quot;name&quot;&quot;: &quot;&quot;The Hidden Impact on the Economy&quot;&quot;
        ///    }}
        ///  ]
        ///}}
        ///
        ///NOW IT IS YOUR TURN. Return EXCLUSIVELY a valid JSON object, generating catchy titles and real reas [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string UserCutPrompt {
            get {
                return ResourceManager.GetString("UserCutPrompt", resourceCulture);
            }
        }
    }
}
