services:
  yt.generate.cuts.worker.videoextraction:
    image: ${DOCKER_REGISTRY-}ytgeneratecutsworkervideoextraction
    build:
      context: .
      dockerfile: YT.Generate.Cuts.Worker.VideoExtraction/Dockerfile
