using Microsoft.Extensions.Logging;
using YoutubeExplode.Converter;
using YoutubeExplode.Videos.Streams;
using YT.Generate.Cuts.Application.Abstractions.Exceptions;
using YT.Generate.Cuts.Application.Abstractions.Interfaces.VideoSource;

namespace YT.Generate.Cuts.Application.VideoExtraction.Youtube;

/// <summary>
/// Download via YoutubeExplode. Mantido como alternativa: é a implementação em
/// processo, sem dependência de executável externo.
/// </summary>
public sealed class YoutubeExplodeVideoDownloader : IVideoDownloader
{
    private readonly YoutubeClientProvider _youtube;
    private readonly string _ffmpegPath;
    private readonly ILogger<YoutubeExplodeVideoDownloader> _logger;

    public YoutubeExplodeVideoDownloader(
        YoutubeClientProvider youtube,
        Microsoft.Extensions.Configuration.IConfiguration configuration,
        ILogger<YoutubeExplodeVideoDownloader> logger)
    {
        _youtube = youtube;
        _ffmpegPath = configuration["FFmpegSettings:BinaryPath"] ?? "ffmpeg";
        _logger = logger;
    }

    public string ProviderName => "YoutubeExplode";

    /// <summary>Em processo: se a aplicação subiu, o provedor existe.</summary>
    public Task<bool> IsAvailableAsync(CancellationToken ct) => Task.FromResult(true);

    public async Task<VideoDownloadResult> DownloadAsync(VideoDownloadRequest request, CancellationToken ct)
    {
        Directory.CreateDirectory(request.TargetDirectory);

        var handle = Guid.NewGuid().ToString("N");
        var videoPath = Path.Combine(request.TargetDirectory, $"video_{handle}.mp4");
        var subtitlePath = Path.Combine(request.TargetDirectory, $"subs_{handle}.srt");

        try
        {
            var youtube = _youtube.Client;
            var videoInfo = await youtube.Videos.GetAsync(request.VideoUrl, ct);
            var duration = videoInfo.Duration ?? TimeSpan.Zero;

            var subtitle = await DownloadSubtitlesAsync(request, subtitlePath, ct);

            var manifest = await youtube.Videos.Streams.GetManifestAsync(request.VideoUrl, ct);

            var videoStream = manifest
                .GetVideoOnlyStreams()
                .Where(s => s.VideoResolution.Height <= request.MaxHeight)
                .GetWithHighestVideoQuality();

            var audioStream = manifest.GetAudioOnlyStreams().GetWithHighestBitrate();

            var conversion = new ConversionRequest(
                ffmpegCliFilePath: _ffmpegPath,
                outputFilePath: videoPath,
                container: new Container("mp4"),
                preset: ConversionPreset.VeryFast,
                environmentVariables: new Dictionary<string, string?>());

            await youtube.Videos.DownloadAsync(
                streamInfos: new IStreamInfo[] { audioStream, videoStream },
                conversion,
                cancellationToken: ct);

            return new VideoDownloadResult(videoPath, subtitle.Path, subtitle.Language, duration);
        }
        catch (OperationCanceledException)
        {
            CleanUp(videoPath, subtitlePath);
            throw;
        }
        catch (Exception ex)
        {
            CleanUp(videoPath, subtitlePath);
            throw VideoSourceErrors.Translate(ex, request.VideoUrl);
        }
    }

    private async Task<(string? Path, string? Language)> DownloadSubtitlesAsync(
        VideoDownloadRequest request, string savePath, CancellationToken ct)
    {
        try
        {
            var manifest = await _youtube.Client.Videos.ClosedCaptions.GetManifestAsync(request.VideoUrl, ct);

            // Mesma regra de escolha do provedor yt-dlp, para os dois caminhos
            // entregarem a legenda do mesmo idioma. A versão anterior caía em
            // "a primeira faixa automática que existir", o que podia devolver
            // uma legenda em coreano para um vídeo em português.
            var choice = SubtitleTrackSelector.Choose(
                manualTags: manifest.Tracks.Where(t => !t.IsAutoGenerated).Select(t => t.Language.Code),
                automaticTags: manifest.Tracks.Where(t => t.IsAutoGenerated).Select(t => t.Language.Code),
                preferredLanguages: request.PreferredSubtitleLanguages);

            if (choice is null)
            {
                _logger.LogWarning(
                    "[{Provider}] Nenhuma legenda nos idiomas pedidos ({Wanted}). Disponíveis: [{Available}].",
                    ProviderName,
                    string.Join(", ", request.PreferredSubtitleLanguages),
                    string.Join(", ", manifest.Tracks.Select(t => t.Language.Code).Distinct().Take(12)));

                return (null, null);
            }

            var track = manifest.Tracks.First(t =>
                string.Equals(t.Language.Code, choice.Tag, StringComparison.OrdinalIgnoreCase) &&
                t.IsAutoGenerated == choice.IsAutomatic);

            await _youtube.Client.Videos.ClosedCaptions.DownloadAsync(track, savePath, cancellationToken: ct);
            return (savePath, track.Language.Code);
        }
        catch (Exception ex) when (ex is not OperationCanceledException)
        {
            _logger.LogWarning("[{Provider}] Não foi possível extrair legendas: {Message}", ProviderName, ex.Message);
            TryDelete(savePath);
            return (null, null);
        }
    }

    private void CleanUp(params string[] paths)
    {
        foreach (var path in paths) TryDelete(path);
    }

    private void TryDelete(string path)
    {
        try
        {
            if (File.Exists(path)) File.Delete(path);
        }
        catch (Exception ex)
        {
            _logger.LogWarning("[{Provider}] Não foi possível remover o parcial {Path}: {Message}", ProviderName, path, ex.Message);
        }
    }
}
