// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YT.Generate.Cuts.Infra.Data.Context;

#nullable disable

namespace YT.Generate.Cuts.Infra.Data.Migrations
{
    [DbContext(typeof(CutContext))]
    [Migration("20260823120000_AddCutDurationPerChannel")]
    partial class AddCutDurationPerChannel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YT.Generate.Cuts.Domain.Entities.Cut", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CutPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("FinallyTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("InitialTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("PublishChannelId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long?>("VideoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PublishChannelId");

                    b.HasIndex("VideoId");

                    b.ToTable("Cuts");
                });

            modelBuilder.Entity("YT.Generate.Cuts.Domain.Entities.Monitoring", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MonitoringChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("PublishChannelId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MonitoringChannelId");

                    b.HasIndex("PublishChannelId");

                    b.ToTable("Monitorings");
                });

            modelBuilder.Entity("YT.Generate.Cuts.Domain.Entities.MonitoringChannel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxCutSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("MinCutSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MonitoringChannels");
                });

            modelBuilder.Entity("YT.Generate.Cuts.Domain.Entities.PublishChannel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypePublish")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("publishChannels");
                });

            modelBuilder.Entity("YT.Generate.Cuts.Domain.Entities.Video", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubtitlePath")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoPath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("YT.Generate.Cuts.Domain.Entities.Cut", b =>
                {
                    b.HasOne("YT.Generate.Cuts.Domain.Entities.PublishChannel", "PublishChannel")
                        .WithMany()
                        .HasForeignKey("PublishChannelId");

                    b.HasOne("YT.Generate.Cuts.Domain.Entities.Video", "Video")
                        .WithMany("Cuts")
                        .HasForeignKey("VideoId");

                    b.Navigation("PublishChannel");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("YT.Generate.Cuts.Domain.Entities.Monitoring", b =>
                {
                    b.HasOne("YT.Generate.Cuts.Domain.Entities.MonitoringChannel", "MonitoringChannel")
                        .WithMany("Monitorings")
                        .HasForeignKey("MonitoringChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YT.Generate.Cuts.Domain.Entities.PublishChannel", "PublishChannel")
                        .WithMany("Monitorings")
                        .HasForeignKey("PublishChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoringChannel");

                    b.Navigation("PublishChannel");
                });

            modelBuilder.Entity("YT.Generate.Cuts.Domain.Entities.Video", b =>
                {
                    b.HasOne("YT.Generate.Cuts.Domain.Entities.MonitoringChannel", "Channel")
                        .WithMany("Videos")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("YT.Generate.Cuts.Domain.Entities.MonitoringChannel", b =>
                {
                    b.Navigation("Monitorings");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("YT.Generate.Cuts.Domain.Entities.PublishChannel", b =>
                {
                    b.Navigation("Monitorings");
                });

            modelBuilder.Entity("YT.Generate.Cuts.Domain.Entities.Video", b =>
                {
                    b.Navigation("Cuts");
                });
#pragma warning restore 612, 618
        }
    }
}
