using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using YoutubeExplode;
using YoutubeExplode.Converter;
using YoutubeExplode.Videos.Streams;
using YT.Generate.Cuts.Application.Abstractions.Interfaces.Commands;

namespace YT.Generate.Cuts.Application.VideoExtraction.Commands.Download;

public class DownloadVideoCommandHandler : ICommandHandler<DownloadVideoCommand, DownloadVideoCommandResponse>
{
    private readonly ILogger<DownloadVideoCommandHandler> _logger;
    private readonly IConfiguration _configuration;

    public DownloadVideoCommandHandler(
        ILogger<DownloadVideoCommandHandler> logger,
        IConfiguration configuration)
    {
        _logger = logger;
        _configuration = configuration;
    }

    public async Task<DownloadVideoCommandResponse> Handle(DownloadVideoCommand command, CancellationToken ct)
    {
        _logger.LogInformation("Iniciando download do video e legendas: {videoUri}", command.videoUri);
        try
        {
            var ffmpegPath = _configuration["FFmpegSettings:BinaryPath"] ?? "ffmpeg";

            if (!Directory.Exists(command.saveDirectory))
                Directory.CreateDirectory(command.saveDirectory);

            var youtube = new YoutubeClient();
            var fileGuid = Guid.NewGuid();
            var videoPath = Path.Combine(command.saveDirectory, $"video_{fileGuid}.mp4");
            var subtitlePath = Path.Combine(command.saveDirectory, $"subs_{fileGuid}.srt");

            var videoInfo = await youtube.Videos.GetAsync(command.videoUri, ct);
            var videoDuration = videoInfo.Duration ?? TimeSpan.Zero;

            string subtitleLanguage = await DownloadSubtitlesAsync(youtube, command.videoUri, subtitlePath, ct);

            var streamManifest = await youtube.Videos.Streams.GetManifestAsync(command.videoUri, ct);

            if (!int.TryParse(_configuration["MaxResolution"], out int maxResolution))
            {
                maxResolution = 720;
            }

            var videoStreamInfo = streamManifest
                .GetVideoOnlyStreams()
                .Where(s => s.VideoResolution.Height <= maxResolution)
                .GetWithHighestVideoQuality();

            var audioStreamInfo = streamManifest
                .GetAudioOnlyStreams()
                .GetWithHighestBitrate();

            var streamInfos = new IStreamInfo[] { audioStreamInfo, videoStreamInfo };

            var conversionRequest = new ConversionRequest(
                ffmpegCliFilePath: ffmpegPath,
                outputFilePath: videoPath,
                container: new Container("mp4"),
                preset: ConversionPreset.VeryFast,
                environmentVariables: new Dictionary<string, string?>()
            );

            await youtube.Videos.DownloadAsync(
                streamInfos: streamInfos,
                conversionRequest,
                cancellationToken: ct
            );

            _logger.LogInformation("Download concluído! Video: {VPath} | Legenda: {SPath} | Idioma: {Lang} | Duração: {Dur}",
                videoPath, subtitlePath, subtitleLanguage, videoDuration);

            return new DownloadVideoCommandResponse(videoPath, subtitlePath, subtitleLanguage, videoDuration);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Falha crítica no processamento do vídeo: {videoUri}", command.videoUri);
            throw;
        }
    }

    private async Task<string> DownloadSubtitlesAsync(YoutubeClient youtube, string videoUri, string savePath, CancellationToken ct)
    {
        try
        {
            var trackManifest = await youtube.Videos.ClosedCaptions.GetManifestAsync(videoUri, ct);

            var trackInfo = trackManifest.TryGetByLanguage("pt") ??
                            trackManifest.TryGetByLanguage("en") ??
                            trackManifest.Tracks.FirstOrDefault(t => t.IsAutoGenerated);

            if (trackInfo != null)
            {
                _logger.LogInformation("Baixando legenda: {lang}", trackInfo.Language.Name);
                await youtube.Videos.ClosedCaptions.DownloadAsync(
                    trackInfo: trackInfo,
                    filePath: savePath,
                    cancellationToken: ct
                );

                return trackInfo.Language.Code;
            }
            else
            {
                _logger.LogWarning("Nenhuma legenda disponível para este vídeo.");
                return string.Empty;
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Não foi possível extrair legendas.");
            return string.Empty;
        }
    }
}